# Generated by Django 4.1 on 2025-05-02 14:25

from django.db import migrations, models
from cinema.models import movie_image_path


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.ImageField(null=True, upload_to=movie_image_path),
        ),
    ]
